<div id="r1-banco">
	<div class="r2-titulo-banco">
		<center>Creando un Banco</center>
	</div>
	<div class="r3-info-banco">
		Las cuentas de banco de Alegra te permiten llevar el control de entradas y salidas de dinero de tu negocio asociados a cuentas de banco o efectivo, tambi&eacute;n puedes llevar el control de tus tarjetas de cr&eacute;dito.
	</div>	
	<div class="r3-video-banco">
		<iframe class="banco-video" src="https://www.youtube.com/embed/mbyIq0KqATM?autohide=2"  allowfullscreen></iframe>
	</div>
</div>
<div id="r2-banco">
	<div class="r2-banco-titulo">
		<p>Sigue estos <font color="#004C43">pasos</font> para crear una nueva cuenta de banco.</p> 
	</div>
	<div class="r2-banco-pasos">
		<div class='r2-banco-pasos1'>
			<p>1. Haz clic en en men&uacute; "Bancos"</p>
			<p>2. Haz clic en el bot&oacute;n "Nuevo banco"</p>
			<p>  3. Selecciona el "Tipo de cuenta" de banco que vas a usar entre las opciones: Banco, Tarjeta de cr&eacute;dito y Efectivo.</p>
			<p>  4. Ingresa el "Nombre de esta cuenta", puede ser un nombre relacionado con sus caracter&iacute;sticas, por ejemplo: 
				BBVA Cuenta de Ahorros, Caja general almac&eacute;n o Tarjeta de Cr&eacute;dito American Express.</p>
			<p>5. Escribe el "N&uacute;mero de tu cuenta", para que puedas identificarla.</p>
			<p>6. Si activaste la funci&oacute;n de multimoneda, selecciona la moneda que usar&aacute;s para el banco que est&aacute;s creando.
	 			M&aacute;s informaci&oacute;n sobre multimoneda aqu&iacute;.</p>
	 		<p>7. Al crear una cuenta de "Banco" o "Efectivo" debes Ingresar el "Saldo inicial" con el que empieza a operar el banco.
	 			Para la opci&oacute;n "Tarjeta Cr&eacute;dito" debes ingresar el "Saldo de la Deuda inicial" (el monto de dinero que has consumido de tu tarjeta de cr&eacute;dito en el momento de crearla en el sistema).</p>
	 		<p> 8. Completa la informaci&oacute;n de la "Fecha" en la cual el saldo es v&aacute;lido.</p>
	 		<p> 9. Puedes agregar una "Descripci&oacute;n" si lo necesitas.</p>
	 		<p>10. Haz clic en "Guardar" y habr&aacute;s creado un nuevo banco.</p>
		</div>
	</div>
</div>