<div id="r1-facturas">
	<div class="r2-titulo-factura">
		<center>C&oacute;mo hacer una Factura de Venta</center>
	</div>
	<div class="r3-info-factura">
		Observa nuestro video especialmente hecho para ti. Aprende a realizar una factura de venta.
	</div>	
	<div class="r3-video-factura">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/5mUmXR4bsQw?autohide=2"  allowfullscreen></iframe>
	</div>

</div>