<div id="r1-importar">
	<div id="r1-importar-como">
		<p>Alegra te ense&ntilde;a a importar tus contactos</p>
		<p>Si tienes tu base de datos de contactos (clientes y proveedores) previamente creada en un archivo o si quieres crear todos tus contactos en Alegra sin necesidad de hacerlo uno a uno, puedes importarlos de forma masiva usando un archivo de Excel en formato xlsx o xls siguiendo los siguientes pasos.</p>
	</div>
</div>
<div id="r2-importar">
	<div id="r2-importar-left">
		<center><p>Paso 1</p></center>
		<div id="r2-importar-paso1">
		Crea una nueva hoja de c&aacute;lculo en Excel para cada uno de tus grupos de contactos, es decir proveedores y/o clientes.
		</div>	
	</div>
	<div id="r2-importar-center1">
		<center><p>Paso 2</p></center>
		<div id="r2-importar-paso2">
			Crea una tabla con 10 columnas y X filas para ingresar la informaci&oacute;n de tus contactos.
		</div>
	</div>
	<div id="r2-importar-center2">
		<center><p>Paso 3</p></center>
		<div id="r2-importar-paso3">			
			Ingresa en la tabla la informaci&oacute;n de tus contactos, el &uacute;nico campo obligatorio es el nombre pero se recomienda completar todos los datos en especial la identificaci&oacute;n, direcci&oacute;n y correo electr&oacute;nico para el env&iacute;o de documentos.
		</div>
	</div>	
	<div id="r2-importar-right">
		<center><p>Paso 4</p></center>
		<div id="r2-importar-paso4">			
			Ingresa en la tabla la informaci&oacute;n de tus contactos, el &uacute;nico campo obligatorio es el nombre pero se recomienda completar todos los datos en especial la identificaci&oacute;n, direcci&oacute;n y correo electr&oacute;nico para el env&iacute;o de documentos.
		</div>
	</div>	
</div>