<div id="index-page">
	<div id="index-intro">
		<div id="index-black" >			
			<center>Software Contable y de Facturacion para Pymes</center>
			<center><h1><a class="btn btn-default btn-lg" href="#" role="button">Conocenos</a></h1></center>			
		</div>		
	</div>	
</div>
<div id="index-r2">
	<div id="left-wrapper">			
	</div>
	<div id="right-wrapper">
			<center>Alegra es un <font color="#10B396">programa de contabilidad y de facturaci&oacute;n</font>, dise&ntilde;ado para gerentes de America Latina.</center>
	</div>
</div>
<div id="index-r3">
	<div id="r3-plan">
		<center><p>Planes</p></center>
	</div>
	<div id="r3-left">
		<p>PYME</p>
		<div id="index-pyme">
			<table class="table table-sm" width="200">
				<tbody>
					<tr>
						<th>100 facturas de venta mensuales</th>
					</tr>
					<tr>
						<th>100 facturas de compra mensuales</th>				
					</tr>
					<tr>
						<th>Cotizaciones </th>
					</tr>
					<tr>
						<th>Soporte Telef&oacute;nico </th>
					</tr>
					<tr>
						<th>2 Uusarios con acceso a Alegra</th>
					</tr>
					<tr>
						<th>Transacciones ilimitadas</th>
					</tr>
					<tr>
						<th>Adjunta hasta 3.000 archivos</th>
					</tr>
					<tr>
						<th>Crea hasta 2 bodegas</th>
					</tr>
				</tbody>	
			</table>
			<p><center class="pyme-first">25 USD/Mes</center></p>
			<p><center>Impuestos incluidos.</center></p>
			<p><center>10% descuento en pago anual.</center></p>
		</div>	
	</div>
	<div id="r3-center">
		<p>PRO</p>
		<div id="index-pro">
			<table class="table table-sm" width="200">
				<tbody>
					<tr>
						<th>1000 facturas de venta mensuales</th>
					</tr>
					<tr>
						<th>Facturas de compra ilimitadas</th>				
					</tr>
					<tr>
						<th>Cotizaciones</th>
					</tr>
					<tr>
						<th>Soporte Telef&oacute;nico </th>
					</tr>
					<tr>
						<th>3 Uusarios con acceso a Alegra</th>
					</tr>
					<tr>
						<th>Transacciones ilimitadas</th>
					</tr>
					<tr>
						<th>Adjunta hasta 10.000 archivos</th>
					</tr>
					<tr>
						<th>Crea hasta 5 bodegas</th>
					</tr>
				</tbody>	
			</table>
			<p><center class="pro-first">45 USD/Mes</center></p>
			<p><center>Impuestos incluidos.</center></p>
			<p><center>10% descuento en pago anual.</center></p>
		</div>
	</div>
	<div id="r3-right">
		<p>PLUS</p>
		<div id="index-plus">
			<table class="table table-sm" width="200">
				<tbody>
					<tr>
						<th>Facturas de venta ilimitada</th>
					</tr>
					<tr>
						<th>Factura de compra ilimitada</th>				
					</tr>
					<tr>
						<th>Cotizaciones</th>
					</tr>
					<tr>
						<th>Soporte Telef&oacute;nico </th>
					</tr>
					<tr>
						<th>5 Uusarios con acceso a Alegra</th>
					</tr>
					<tr>
						<th>Transacciones ilimitadas</th>
					</tr>
					<tr>
						<th>Adjunta hasta 20.000 archivos</th>
					</tr>
					<tr>
						<th>Crea bodegas ilimitadas</th>
					</tr>
				</tbody>	
			</table>
			<p><center class="plus-first">75 USD/Mes</center></p>
			<p><center>Impuestos incluidos.</center></p>
			<p><center>10% descuento en pago anual.</center></p>
		</div>
	</div>
	
</div>