<div id="info-page">
	<div id="info-intro">			
			<center> <h1><font color="#10B3A3">Alegra</font> te permite</h1></center>		
	</div>	
</div>

<div id="info-r2">
	<div id="info-left">
		<table>
			<tr>
				<th><img src="../image/facturas.png" align="left"></th>
				<th>Crear facturas o cuentas de cobro con diferentes dise&ntilde;os, env&iacute;alas por correo e impr&iacute;melas con todos los requisitos de la DIAN. Para el r&eacute;gimen com&uacute;n o simplificado.</th>
			</tr>
			<tr>
				<th><img src="../image/gastos.png"></th>
				<th>Controlar y Administrar en su totalidad tus gastos y lo que debes a tus proveedores.</th>
			</tr>
			<tr>
				<th><img src="../image/bancos.png"></th>
				<th>Controlar y conciliar tus cuentas bancarias para un mejor manejo de tu dinero.</th>
			</tr>
			<tr>
				<th><img src="../image/inventarios.png"></th>
				<th>Organizar y controlar lo que sale y entra en tu empresa.</th>
			</tr>
		</table>
	</div>
	<div id="info-right">
		<table>
			<tr>
				<th><img src="../image/usuarios.png" align="left"></th>
				<th>Ordenar la informaci&oacute;n de tus clientes y proveedores.</th>
			</tr>
			<tr>
				<th><img src="../image/reportes.png"></th>
				<th>Consultar reportes inteligentes que observas en tiempo real desde tu pc o movil.</th>
			</tr>
			<tr>
				<th><img src="../image/movil.png"></th>
				<th>Descargar la App y accede a todas las funciones de Alegra estes donde estes.</th>
			</tr>
			<tr>
				<th><img src="../image/api.png"></th>
				<th>Enlazar otras aplicaciones a Alegra utilizando nuestra API, sencilla de integrar.</th>
			</tr>
		</table>			
	</div>
</div>
<div id="info-r3">
	<div id="intro-r3">
		<center> <h1>M&aacute;s funciones que te permite <font color="#10B3A3">Alegra</font> para hacer tu empresa m&aacute;s eficiente</h1></center>
	</div>
	<div class="div-3">
		<div class="info-r3-left">
			<center><h3>Notificaciones del negocio</h3></center>
			<center><h4>Como administrador de la cuenta recibe notificaciones de los diferentes movimientos en Alegra.</h4></center>
		</div>
		<div class="info-r3-center">
			<center><h3>Control de Usuarios</h3></center>
			<center><h4>Controla las acciones de cada usuario en la plataforma de acuerdo a su Perfil.</h4></center>
		</div>
		<div class="info-r3-right">
			<center><h3>Adjunta archivos</h3></center>
			<center><h4>Adjunta archivos directamente en la plataforma: recibos, cotizaciones, facturas, tarjetas de presentacion, todo organizado en un solo lugar.</h4></center>
		</div>
	</div>

</div>