

	<div class="agregar" >
		<div class="iconos"  >
			<h2><span class="glyphicon glyphicon-inbox"></span>Contactos  <a class="btn btn-primary btn-lg" href="<?php echo $this->url(array('controller'=>'index','action'=>'showform'),'show') ?>" role="button">Nuevo Contacto +</a>
		</div>
	</div>	
	

	<script>
		Ext.define('Contactos',{
			extend: 'Ext.data.Model',
			fields: ['id','name','identification','phonePrimary','observations']
			});	

		var store = Ext.create('Ext.data.Store', {
			model: 'Contactos',
			pageSize: 20,
			autoLoad: true,
			proxy: {
				type: 'ajax',
				url:  'https://app.alegra.com/api/v1/contacts/',
				method: 'GET',
				//pageParam: false, //to remove param "page"
			    //startParam: 0, //to remove param "start"
			    //limitParam: 25, //to remove param "limit"
			    //noCache: false 
				reader: {
					type: 'json',
					rootProperty: 'root',
                    successProperty: 'success',
					id: 'id',
					totalProperty: 'total',
					},
				headers: {
					Accept : 'application/json',
					Authorization: 'Basic aWduYWNpb19zYWx2YXRpZXJyYUBob3RtYWlsLmNvbTo0ZTk3NDkyNGMyYTBjM2Y1NDVjMA=='
						}				
				}
			});

		
		
	

		Ext.create('Ext.grid.Panel',{
			//title: '<center>Contactos</center>',
		    id: 'cat_categoriesGrid',
		    store: store,
		    
		    columns: [
		              { text: '#', dataIndex: 'id', width: 35 },
		              { text: '<center>Nombre</center>', dataIndex: 'name', width: 210},
		              {text: '<center>Identificacion</center>', dataIndex: 'identification',width: 210},
		              {text: '<center>Telefono 1</center>', dataIndex: 'phonePrimary',width: 210},
		              {text: '<center>Observaciones</center>', dataIndex:'observations',width: 210},
		              {
			              	text: '<center>Acciones</center>',
			              	width: 125,
		            	    xtype: 'actioncolumn',
		            	    items: [{
		            	    		icon: '<?php echo $this->baseUrl('image/zoom.png');?>', // Use a URL in the icon config
		            	            tooltip: 'show',
		            	            handler: function(grid, rowIndex, colIndex, a, b, c) {
		            	            	var rec = grid.getStore().getAt(rowIndex);
		            	            	var id = rec.get('id');
		            	            	location.href = "view/id/" + id;
		            	            	}
		            	    		},
				            	    {
		            	    		icon: '<?php echo $this->baseUrl('image/page_edit.png');?>', // Use a URL in the icon config
		            	            tooltip: 'Edit',
		            	            handler: function(grid, rowIndex, colIndex, a, b, c) {
		            	            	var rec = grid.getStore().getAt(rowIndex);
		            	            	var id = rec.get('id');
		            	            	location.href = "edit/id/" + id;
		            	            	}
		            	    		},
		            	    		{
			            	    		icon: '<?php echo $this->baseUrl('image/delete.png');?>', // Use a URL in the icon config
			            	            tooltip: 'Delete',
			            	            handler: function(grid, rowIndex, colIndex, a, b, c) {
			            	            	var rec = grid.getStore().getAt(rowIndex);
			            	            	var id = rec.get('id');			            	            	
			            	            	Ext.Msg.show({
			            	            	     title:'Eliminar usuario',
			            	            	     msg: 'Estas seguro de querer eliminar este usuario?',
			            	            	     buttons: Ext.Msg.YESNO,
			            	            	     icon: Ext.Msg.QUESTION,
			            	            	     buttonText: {
				            	            	     yes: "Si", 
				            	            	     no: "No",
				            	            	     },
			            	            	     fn: function(btnId) {
					            	                    if (btnId == 'yes') {

					            	                    	location.href = "delete/id/" + id; 					            	                    	           

					            	                    } else {
					            	                        store.rejectChanges();
					            	                    }
					            	                },
			            	            	});
			            	            	
			            	            	
			            	            	}
			            	    		},

		            	    ]
		            	}
		          ],
		    
			width: 1010,
			height: 345,
			loadMask : false,
			dockedItems: [{
		           xtype: 'pagingtoolbar',
		           store: store,   // same store GridPanel is using		          
		           dock: 'bottom',
		           displayInfo: true,
		           beforePageText: 'Pagina',
		           afterPageText: 'de {0}',
		           displayMsg: 'Contactos {0} - {1} de {2}',
		           emptyMsg: "No se encontraron contactos",
		           
		       }],
			style: 'margin:0 auto;margin-top:40px;margin-bottom:15px;',
		    enableColLock:false,
		    viewConfig: {
		        loadingText: "Cargando..."
		    },
		    //selModel: new Ext.grid.RowSelectionModel({singleSelect:false}),
		    renderTo: Ext.getBody()
		});

		
		
	//alert(store);
	</script>

	

<?php //$phpNative = $this->response;?>
