<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<link rel='stylesheet' type='text/css' href=<?php echo $this->baseUrl('css/mycss.css'); ?> />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/classic/theme-classic/resources/theme-classic-all.css" rel="stylesheet" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/ext-all.js"></script>
  
<title><?php echo $this->title;?></title>

</head>
<body>

	<header>
		<div class="logo">
			<h1><img alt="Brand" src="<?php echo $this->baseUrl('image/alegra.jpg');?>" width="60" height="60">Alegra</h1>
		</div>
		<nav class="navbar navbar-default">
  			<div class="container-fluid">
    			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <ul class="nav navbar-nav">
			        <li class="active"><a href="#">Inicio <span class="sr-only">(current)</span></a></li>
			        <li><a href="#">Ingresos</a></li>
			        <li><a href="#">Gastos</a></li>
			        <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contactos <span class="caret"></span></a>
			          <ul class="dropdown-menu">
			            <li><a href="href=<?php echo $this->baseUrl(); ?>">Lista de contactos</a></li>
			            <li role="separator" class="divider"></li>
			            <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'showform'),'show') ?>">Agregar nuevo contacto</a></li>
			            <li role="separator" class="divider"></li>
			            <li><a href="#">Extra</a></li>
			          </ul>
			        </li>
			        <li><a href="#">Inventario</a></li>
			        <li><a href="#">Bancos</a></li>
			      </ul> 
    			</div>    			
  			</div>
		</nav>	
	</header>
	
	
	<div class="content">
	<?php  echo $this->layout()->content; ?>
	</div>
	
	<footer>
		<div class="copy">	
			<div class='ayuda'>
					<h4>Ayudas paso a paso</h4>
					<lu class="enlace">
						<li>Como crear una factura de venta</li>
						<li>Como crear una factura de proveedor</li>
						<li>Como importar contactos</li>
						<li>Como registra una cuenta de banco</li>
						<li>Como registrar un pago a una factura de venta</li>
						<li>Como crear una nota credito</li>
					</lu>
			</div>
			<div class='support'>
				<h4>Soporte</h4>
				<lu class="enlace2">
					<li>Conactanos</li>
					<li>Centro de ayuda</li>
					<li>Manual de primeros pasos de alegra</li>
					<li>Plan de referidos</li>
					<li>Comparte tu historia</li>
				</lu>
			</div>
			<div class='masAyuda'>
				<h4>Contactos</h4>
				<lu class="enlace3">
					<li>Como crear un cliente?</li>
					<li>Como importar contactos?</li>
				</lu>
			</div>
		</div>
	</footer>

</body>
</html>