<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application</title>
</head>
<body>
	<div id="errorWrapper">
	  <center><h1>Ha ocurrido un error</h1></center>
	  <center><h2><?php echo $this->message ?></h2></center>
	  <center><h3>Nuestro super equipo esta dispuesto a ayudarte</h3></center>
	  <img src="../image/alegra_jedi.png" align="center"></img>
	  <?php if (isset($this->exception)): ?>
	  
	  <h3>Exception information:</h3>
	  <p>
	      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
	  </p>
	
	  <h3>Stack trace:</h3>
	  <pre><?php echo $this->exception->getTraceAsString() ?>
	  </pre>
	
	  <h3>Request Parameters:</h3>
	  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
	  </pre>
	
	  <?php endif ?>
	</div>
</body>
</html>
